# This is a basic workflow to help you get started with Actions

name: CI - Swift Run Tests

# Controls when the action will run. Triggers the workflow on push or pull request
on: [push]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macOS-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Generate xcodeproj
      run: swift package generate-xcodeproj

    # Runs a set of commands using the runners shell
    - name: Run tests
      run: xcodebuild test -destination 'name=iPhone 11' -scheme 'Analytics-Package'
